### ISSUE TITLE
Some code inside comments gets highlighted as code, not as comment

### ISSUE THREAD

**Issue by anton-trunov** [as1ndu/scilla#2]
E.g. try it on something like
```
(* Some 0 *)
```
and you'll see `Some` highlighted as a constructor.

**Comment by as1ndu** [comment]
it turns out this issue arises when a comment is started after a tab or space. I have fixed this to allow comments after whitespaces & tabs to be highlighted as comments.

**Comment by anton-trunov** [comment]
Awesome! If you could push an update to the marketplace, I would help with testing

**Comment by as1ndu** [comment]
Ok, I have done that. Let me know if it fixes issues #1 , #2
 & #3

**Comment by anton-trunov** [comment]
Cool, it works!
